export const operators = {
  $eq      : (field, value) => `= ${value}`,
  $ne      : (field, value) => `!= ${value}`,
  $gt      : (field, value) => `> ${value}`,
  $lt      : (field, value) => `< ${value}` ,
  $gte     : (field, value) => `>= ${value}`,
  $lte     : (field, value) => `<= ${value}`,
  $starts  : (field, value) => `LIKE '${value}%'`,
  $ends    : (field, value) => `LIKE '%${value}`,
  $cont    : (field, value) => `LIKE '%${value}%'`,
  $excl    : (field, value) => `NOT LIKE '%${value}%'`,
  $in      : (field, value) => `IN ${value}`,
  $notin   : (field, value) => `NOT IN ${value}`,
  $isnull  : (field, value) => `IS NULL ${value}`,
  $notnull : (field, value) => `IS NOT NULL ${value}`,
  $between : (field, value) => `BETWEEN ${value}`,
  $eqL     : (field, value) => `LOWER(${field}) = ${value}`,
  $neL     : (field, value) => `LOWER(${field}) != ${value}`,
  $startsL : (field, value) => `LIKE|ILIKE '${value}%'`,
  $endsL   : (field, value) => `LIKE|ILIKE '%${value}'`,
  $contL   : (field, value) => `LIKE|ILIKE '%${value}%'`,
  $exclL   : (field, value) => `NOT LIKE|ILIKE '%${value}%'`,
  $inL     : (field, value) => `LOWER(${field}) IN ${value}`,
  $notinL  : (field, value) => `LOWER(${field}) NOT IN ${value}`,
};